/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_HelloWorld */

#ifndef _Included_com_example_testndk_HelloWorld
#define _Included_com_example_testndk_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testndk_HelloWorld
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testndk_HelloWorld_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
